# Generated by Django 2.2.4 on 2019-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('lastVisit', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('lastActiveDate', models.DateTimeField()),
                ('minNumberOfVisitsPerWeek', models.IntegerField(default=0)),
                ('maxNumberOfVisitsPerWeek', models.IntegerField(default=0)),
                ('numberOfVisitsDuringCurrentMonth', models.IntegerField(default=0)),
                ('averageNumberOfVisitsPerMonth', models.IntegerField(default=0)),
            ],
        ),
    ]
