# Generated by Django 2.2.4 on 2019-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pnTemplate', models.TextField()),
                ('smsTemplate', models.TextField()),
                ('numberOfPoints', models.IntegerField(default=1)),
                ('costPerUser', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
