# Generated by Django 2.2.4 on 2019-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190812_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaignSentPNS',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='campaignSentSMS',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='costOfRetention',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='retentionDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
