# Generated by Django 2.2.4 on 2019-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190814_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campaignSentPNS',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='campaignSentSMS',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
